osf/NotoRoundedOSF-CondensedExtraLight.otd: rounded/NotoRounded-CondensedExtraLight.otd
	mkdir -p osf
	python osf.py "Condensed" ExtraLight 0.1.2
rounded/NotoRounded-CondensedExtraLight.otd: sans/NotoSans-CondensedExtraLight.otd
	mkdir -p rounded
	python round.py "Condensed" ExtraLight 0.1.2
sans/NotoSans-CondensedExtraLight.otd: sans/NotoSans-CondensedExtraLight.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedExtraLight.otd: rounded/NotoRounded-SemiCondensedExtraLight.otd
	mkdir -p osf
	python osf.py "SemiCondensed" ExtraLight 0.1.2
rounded/NotoRounded-SemiCondensedExtraLight.otd: sans/NotoSans-SemiCondensedExtraLight.otd
	mkdir -p rounded
	python round.py "SemiCondensed" ExtraLight 0.1.2
sans/NotoSans-SemiCondensedExtraLight.otd: sans/NotoSans-SemiCondensedExtraLight.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-ExtraLight.otd: rounded/NotoRounded-ExtraLight.otd
	mkdir -p osf
	python osf.py "" ExtraLight 0.1.2
rounded/NotoRounded-ExtraLight.otd: sans/NotoSans-ExtraLight.otd
	mkdir -p rounded
	python round.py "" ExtraLight 0.1.2
sans/NotoSans-ExtraLight.otd: sans/NotoSans-ExtraLight.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-CondensedLight.otd: rounded/NotoRounded-CondensedLight.otd
	mkdir -p osf
	python osf.py "Condensed" Light 0.1.2
rounded/NotoRounded-CondensedLight.otd: sans/NotoSans-CondensedLight.otd
	mkdir -p rounded
	python round.py "Condensed" Light 0.1.2
sans/NotoSans-CondensedLight.otd: sans/NotoSans-CondensedLight.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedLight.otd: rounded/NotoRounded-SemiCondensedLight.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Light 0.1.2
rounded/NotoRounded-SemiCondensedLight.otd: sans/NotoSans-SemiCondensedLight.otd
	mkdir -p rounded
	python round.py "SemiCondensed" Light 0.1.2
sans/NotoSans-SemiCondensedLight.otd: sans/NotoSans-SemiCondensedLight.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-Light.otd: rounded/NotoRounded-Light.otd
	mkdir -p osf
	python osf.py "" Light 0.1.2
rounded/NotoRounded-Light.otd: sans/NotoSans-Light.otd
	mkdir -p rounded
	python round.py "" Light 0.1.2
sans/NotoSans-Light.otd: sans/NotoSans-Light.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-CondensedRegular.otd: rounded/NotoRounded-CondensedRegular.otd
	mkdir -p osf
	python osf.py "Condensed" Regular 0.1.2
rounded/NotoRounded-CondensedRegular.otd: sans/NotoSans-Condensed.otd
	mkdir -p rounded
	python round.py "Condensed" Regular 0.1.2
sans/NotoSans-Condensed.otd: sans/NotoSans-Condensed.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedRegular.otd: rounded/NotoRounded-SemiCondensedRegular.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Regular 0.1.2
rounded/NotoRounded-SemiCondensedRegular.otd: sans/NotoSans-SemiCondensed.otd
	mkdir -p rounded
	python round.py "SemiCondensed" Regular 0.1.2
sans/NotoSans-SemiCondensed.otd: sans/NotoSans-SemiCondensed.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-Regular.otd: rounded/NotoRounded-Regular.otd
	mkdir -p osf
	python osf.py "" Regular 0.1.2
rounded/NotoRounded-Regular.otd: sans/NotoSans-Regular.otd
	mkdir -p rounded
	python round.py "" Regular 0.1.2
sans/NotoSans-Regular.otd: sans/NotoSans-Regular.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-CondensedMedium.otd: rounded/NotoRounded-CondensedMedium.otd
	mkdir -p osf
	python osf.py "Condensed" Medium 0.1.2
rounded/NotoRounded-CondensedMedium.otd: sans/NotoSans-CondensedMedium.otd
	mkdir -p rounded
	python round.py "Condensed" Medium 0.1.2
sans/NotoSans-CondensedMedium.otd: sans/NotoSans-CondensedMedium.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedMedium.otd: rounded/NotoRounded-SemiCondensedMedium.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Medium 0.1.2
rounded/NotoRounded-SemiCondensedMedium.otd: sans/NotoSans-SemiCondensedMedium.otd
	mkdir -p rounded
	python round.py "SemiCondensed" Medium 0.1.2
sans/NotoSans-SemiCondensedMedium.otd: sans/NotoSans-SemiCondensedMedium.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-Medium.otd: rounded/NotoRounded-Medium.otd
	mkdir -p osf
	python osf.py "" Medium 0.1.2
rounded/NotoRounded-Medium.otd: sans/NotoSans-Medium.otd
	mkdir -p rounded
	python round.py "" Medium 0.1.2
sans/NotoSans-Medium.otd: sans/NotoSans-Medium.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-CondensedBold.otd: rounded/NotoRounded-CondensedBold.otd
	mkdir -p osf
	python osf.py "Condensed" Bold 0.1.2
rounded/NotoRounded-CondensedBold.otd: sans/NotoSans-CondensedBold.otd
	mkdir -p rounded
	python round.py "Condensed" Bold 0.1.2
sans/NotoSans-CondensedBold.otd: sans/NotoSans-CondensedBold.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedBold.otd: rounded/NotoRounded-SemiCondensedBold.otd
	mkdir -p osf
	python osf.py "SemiCondensed" Bold 0.1.2
rounded/NotoRounded-SemiCondensedBold.otd: sans/NotoSans-SemiCondensedBold.otd
	mkdir -p rounded
	python round.py "SemiCondensed" Bold 0.1.2
sans/NotoSans-SemiCondensedBold.otd: sans/NotoSans-SemiCondensedBold.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-Bold.otd: rounded/NotoRounded-Bold.otd
	mkdir -p osf
	python osf.py "" Bold 0.1.2
rounded/NotoRounded-Bold.otd: sans/NotoSans-Bold.otd
	mkdir -p rounded
	python round.py "" Bold 0.1.2
sans/NotoSans-Bold.otd: sans/NotoSans-Bold.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-CondensedExtraBold.otd: rounded/NotoRounded-CondensedExtraBold.otd
	mkdir -p osf
	python osf.py "Condensed" ExtraBold 0.1.2
rounded/NotoRounded-CondensedExtraBold.otd: sans/NotoSans-CondensedExtraBold.otd
	mkdir -p rounded
	python round.py "Condensed" ExtraBold 0.1.2
sans/NotoSans-CondensedExtraBold.otd: sans/NotoSans-CondensedExtraBold.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-SemiCondensedExtraBold.otd: rounded/NotoRounded-SemiCondensedExtraBold.otd
	mkdir -p osf
	python osf.py "SemiCondensed" ExtraBold 0.1.2
rounded/NotoRounded-SemiCondensedExtraBold.otd: sans/NotoSans-SemiCondensedExtraBold.otd
	mkdir -p rounded
	python round.py "SemiCondensed" ExtraBold 0.1.2
sans/NotoSans-SemiCondensedExtraBold.otd: sans/NotoSans-SemiCondensedExtraBold.ttf
	otfccdump --ignore-hints $< -o $@

osf/NotoRoundedOSF-ExtraBold.otd: rounded/NotoRounded-ExtraBold.otd
	mkdir -p osf
	python osf.py "" ExtraBold 0.1.2
rounded/NotoRounded-ExtraBold.otd: sans/NotoSans-ExtraBold.otd
	mkdir -p rounded
	python round.py "" ExtraBold 0.1.2
sans/NotoSans-ExtraBold.otd: sans/NotoSans-ExtraBold.ttf
	otfccdump --ignore-hints $< -o $@

